# Generated by Django 5.2.16 on 2026-07-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversionState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("PST_TO_UTC", "PST_TO_UTC"),
                            ("UTC_TO_PST", "UTC_TO_PST"),
                        ],
                        default="PST_TO_UTC",
                        max_length=20,
                    ),
                ),
                ("batch", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
